language: objective-c
osx_image: xcode7.2
before_install:
  - pip install codecov
after_success:
  - codecov
script:
 - xctool -scheme Health-Monitor -workspace Health-Monitor.xcworkspace -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
