language: objective-c
osx_image: xcode7.2
before_install:  # to fix xctool issue since Xcode 7.3
  brew uninstall xctool && brew install --HEAD xctool
script:
 - xctool -scheme Health-Monitor -workspace Health-Monitor.xcworkspace -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test
after_success:
  - bash <(curl -s https://codecov.io/bash)
